source 'https://rubygems.org'
ruby '2.2.1'

gem 'rails', '4.0.3'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap'

gem 'humanize'

gem 'progressbar'

#gem 'chunky_png'
gem 'oily_png'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

# elasticsearch
gem 'active_model_serializers', '~> 0.9.0'
gem 'elasticsearch'
gem 'hashie'
gem 'typhoeus'
gem 'faraday_middleware' # for AWS signed elasticsearch
gem 'faraday_middleware-aws-signers-v4' # for AWS signed elasticsearch

gem 'puma' # Puma is now our webserver.
gem 'rails_12factor'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use thin in development
group :development do
  gem 'capistrano-rails', '~> 1.1.1'
  gem 'capistrano-bundler', '~> 1.1.2'
end

group :production do
  gem 'pg' # keep heroku happy.
end
